title: Chetan Ranpariya
logo: /assets/img/logo.png
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/chetan-ranpariya/">LinkedIn</a> |
  <a href="https://github.com/ranpariyachetan">GitHub</a>
 
  <br>
  I am a software professional working as a Principal Software Engineer at Autodesk.
  Recently I developed interest in Machine Learning and AI which is driving the industry very fast.
  I am currently learning Data Science and Machine Learning concepts.
  <br>
  </p>

theme: jekyll-theme-minimal
